export const GenreMap: Map<number, string> = new Map<number, string>([
    [0, 'ACTION'],
    [1, 'ADVENTURE'],
    [2, 'ALT_HIST'],
    [3, 'ANTHOLOGY'],
    [4, 'ARCHITECTURE'],
    [5, 'BIOGRAPHY'],
    [6, 'BUSINESS'],
    [7, 'CHICK_LIT'],
    [8, 'CHILDREN'],
    [9, 'CLASSIC'],
    [10, 'COMIC'],
    [11, 'COOK'],
    [12, 'CRAFTS'],
    [13, 'CRIME'],
    [14, 'DICTIONARY'],
    [15, 'DRAMA'],
    [16, 'ENCYCLOPEDIA'],
    [17, 'FAIRYTALE'],
    [18, 'FANTASY'],
    [19, 'GRAPHIC_NOVEL'],
    [20, 'GUIDE'],
    [21, 'HEALTH'],
    [22, 'HISTORY'],
    [23, 'HIST_FIC'],
    [24, 'HOME_GARDEN'],
    [25, 'HORROR'],
    [26, 'JOURNAL'],
    [27, 'MATH'],
    [28, 'MYSTERY'],
    [29, 'PHILOSOPHY'],
    [30, 'PICTURE'],
    [31, 'POETRY'],
    [32, 'POLITICAL'],
    [33, 'PRAYER'],
    [34, 'RELIGION'],
    [35, 'ROMANCE'],
    [36, 'SATIRE'],
    [37, 'SCIFI'],
    [38, 'SELFHELP'],
    [39, 'SHORT'],
    [40, 'SPIRITUALITY'],
    [41, 'SUSPENSE'],
    [42, 'TEXTBOOK'],
    [43, 'THRILLER'],
    [44, 'TRAVEL'],
    [45, 'WESTERN'],
]);

export const MIN_GENRE: number = 0;
export const MAX_GENRE: number = 45;
