export const GenreMap: Map<number, string> = new Map<number, string>([
    [0, 'ACTION'],
    [1, 'ADVENTURE'],
    [2, 'ANTHOLOGY'],
    [3, 'ARCHITECTURE'],
    [4, 'BIOGRAPHY'],
    [5, 'BUSINESS'],
    [6, 'CHILDREN'],
    [7, 'COMIC'],
    [8, 'COOK_FOOD'],
    [9, 'CRAFTS'],
    [10, 'CRIME'],
    [11, 'DICTIONARY'],
    [12, 'DRAMA'],
    [13, 'ENCYCLOPEDIA'],
    [14, 'FAIRYTALE'],
    [15, 'FANTASY'],
    [16, 'GUIDE'],
    [17, 'HEALTH'],
    [18, 'HISTORY'],
    [19, 'HOME_GARDEN'],
    [20, 'HORROR'],
    [21, 'JOURNAL'],
    [22, 'MATH'],
    [23, 'MYSTERY'],
    [24, 'PHILOSOPHY'],
    [25, 'PICTURE'],
    [26, 'POETRY'],
    [27, 'POLITICAL'],
    [28, 'PRAYER'],
    [29, 'RELIGION'],
    [30, 'ROMANCE'],
    [31, 'SATIRE'],
    [32, 'SCIFI'],
    [33, 'SELFHELP'],
    [34, 'SHORT'],
    [35, 'SPIRITUALITY'],
    [36, 'SUSPENSE'],
    [37, 'TEXTBOOK'],
    [38, 'THRILLER'],
    [39, 'TRAVEL'],
    [40, 'WESTERN'],
]);

export const MIN_GENRE: number = 0;
export const MAX_GENRE: number = 40;
